### ISSUE TITLE
Grouping cards from one story (by adding "rows")

### ISSUE THREAD

**Issue by bartaz** [WTTechLabs/taskboard#25]
There should be a possibility of visually grouping cards that represent tasks for one story.
Sometimes on real scrum taskboaards it's done with 'rows' like: http://www.mountaingoatsoftware.com/system/hidden_asset/file/29/MockedTaskBoard.jpg

Currently you can mark cards with colour or tags, but tags are not so visible and 5 default colours may be not enough.

Easiest solution is to add more colours (maybe customisable) or some other way of grouping cards.

**Comment by aleksandersumowski** [comment]
How much work would it be to add proper story lanes? Any rough estimates?

**Comment by bartaz** [comment]
Too long.
Current taskboard model is designed only for columns, not rows. This will add a bit complexity to the model and to UI and will require quite a lot effort.

**Comment by bartaz** [comment]
Estimations:
- basics (rows model, basic UI) 3SP
- additional UI (drag 'n' drop, etc) 2SP

**Comment by aleksandersumowski** [comment]
hmm, does 
" bartaz  merged branch 'rows' into done" 
commit comment means that this feature is now completed?

**Comment by bartaz** [comment]
It's completed, but not yet officially released (not in master branch).
We plan a release to take place on Monday next week (24.08.2009)

**Comment by rakk** [comment]
09.08.24 Governor Bay
