### ISSUE TITLE
Clonning taskboard

### ISSUE THREAD

**Issue by bartaz** [WTTechLabs/taskboard#6]
I would like to have a possibility of creating new taskboard based of one preselected (kind of cloning).

What should be cloned:
- columns
- cards in each column
  - card issue link, name, notes, tags
  - card ideal hours / burndown (?)

**Comment by bartaz** [comment]
Estimation:
- clone columns and cards (no hours/burndown) 3SP
- clone cards with hours 1SP
- options for cloning 3SP

**Comment by rakk** [comment]
09.08.24 Governor Bay
