### ISSUE TITLE
Show help tips for editable card fields

### ISSUE THREAD

**Issue by bartaz** [WTTechLabs/taskboard#7]
Sometimes it's not clear what should be done to save/cancel editing of what should be entered in edited field.
Some king of help tip should be shown to help users.

For example:
- Description: 'To save press Enter'
- Notes: basics of Markdown syntax
- Tags: 'To add more than one tag use "," f.e. tag1, tag2'

**Comment by bartaz** [comment]
Estimate:
- help tips 2SP

**Comment by rakk** [comment]
IMHO tip should be visible only when the field is focused
