### ISSUE TITLE
User:Digest error not found during db:migrate

### ISSUE THREAD

**Issue by maciej** [WTTechLabs/taskboard#78]
When running the db:migrate rake task I get the following error:

uninitialized constant User::Digest
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:105:in `const_missing'
/srv/d_dunnart/var/www/taskboard/releases/20100211162134/app/models/user.rb:56:in`encrypted_password'
/srv/d_dunnart/var/www/taskboard/releases/20100211162134/app/models/user.rb:32:in `password='
[...more stack trace follows...]

That happens during the AddDefaultUsers migration

My Ruby version is:
# ruby -v

ruby 1.8.6 (2008-08-11 patchlevel 287) [i486-linux]
Ruby Enterprise Edition 20090610

**Comment by maciej** [comment]
Fixed in http://github.com/maciej/taskboard/tree/issue-78
Feel free to pull.

**Comment by maciej** [comment]
doh!, sorry for the dup...

**Comment by bartaz** [comment]
No problem!
At least it seems that it breaks for more people than we expected and needs fixing soon.

**Comment by bartaz** [comment]
And BTW, we need more users that fix the bugs they find ;)

**Comment by maciej** [comment]
At your service. Speaking of fixing bugs and writing code I have some other ideas lining up for TaskBoard, but first I need to find time for these.
